default:
  image: node:12.18.3

stages:
  - test
  - deploy
  - skills
  - post deploy

.default_rules: &default_rules
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $REGENERATE_SKILL_JSONS == null

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: DAST.gitlab-ci.yml

variables:
  DAST_WEBSITE: https://${SERVER_ADDR}

deploy:
  <<: *default_rules
  needs: []
  stage: deploy
  script:
    - source ./scripts/setup-ssh.sh
    - ssh -p $SSH_PORT $SERVER_USER@$SERVER_ADDR 'bash -s' < ./scripts/deploy.sh
  environment:
    name: production
    url: https://${SERVER_ADDR}

regenerate jsons:
  stage: skills
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm
  script:
    - npm update --cache .npm --prefer-offline
    - source ./scripts/setup-ssh.sh
    - scripts/regenerate-skill-jsons.sh
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $REGENERATE_SKILL_JSONS

dast:
  <<: *default_rules
  stage: post deploy

automated tests:
  <<: *default_rules
  stage: post deploy
  trigger: nfriend/website-3.0-tests
