version: '3.7'

services:
    nginx:
        image: nginx-image
        container_name: nginx-container
        build: ./nginx
        ports:
            - '80:80'
            - '443:443'
            - '18734:18734'
            - '9300:9300'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - nginx-certs-volume:/etc/letsencrypt/live
            - ./nginx/logs:/etc/nginx/logs
            - ./node_modules/@nathanfriend/website-3.0:/etc/nginx/html
            - ./node_modules/@nathanfriend/inspirograph:/etc/nginx/html/inspirograph
            - ./node_modules/@nathanfriend/roggle:/etc/nginx/html/roggle
            - ./node_modules/@nathanfriend/cooltojs:/etc/nginx/html/cooltojs
            - ./node_modules/@nathanfriend/theremin:/etc/nginx/html/theremin
            - ./node_modules/@nathanfriend/origins-host:/etc/nginx/html/origins
            - ./node_modules/@nathanfriend/webgl-chess:/etc/nginx/html/webgl-chess
            - ./node_modules/@nathanfriend/nfjs-demo:/etc/nginx/html/nfjs
            - ./node_modules/@nathanfriend/mandelbrot:/etc/nginx/html/mandelbrot
            - ./node_modules/@nathanfriend/fortune-flash-briefings/update-fortune-cookie.js:/etc/periodic/daily/update-fortune-cookie
            - ./node_modules/@nathanfriend/fortune-flash-briefings/update-oddly-specific-fortunes.js:/etc/periodic/daily/update-oddly-specific-fortunes
            - nginx-flash-briefings-volume:/etc/nginx/html/flash-briefings
            - ./node_modules/@nathanfriend/rook:/etc/nginx/html/rook
            - ./static/skills:/etc/nginx/html/skills
            - ./static/ahholyjesus:/etc/nginx/html/ahholyjesus
            - ./static/probe:/etc/nginx/html/probe
            - ./static/site_archive:/etc/nginx/html/site_archive
            - ./static/WordCloud:/etc/nginx/html/WordCloud
            - ./static/wedding:/etc/nginx/html/wedding
            - ./static/battleship.pdf:/etc/nginx/battleship.pdf
        networks:
            - inspirograph-network
        environment:
            - USE_DEV_CERTS=true
        restart: always
    php:
        image: inspirograph-php-image
        container_name: inspirograph-php-container
        build: ./php
        volumes:
            - ./node_modules/@nathanfriend/inspirograph:/etc/nginx/html/inspirograph
            - ./node_modules/@nathanfriend/rook:/etc/nginx/html/rook
            - ./static/site_archive:/etc/nginx/html/site_archive
        networks:
            - inspirograph-network
        restart: always
    mysql:
        image: inspirograph-mysql-image
        container_name: inspirograph-mysql-container
        build: ./mysql
        volumes:
            - ./mysql/conf:/etc/mysql/conf.d
            - inspirograph-mysql-volume:/var/lib/mysql
        networks:
            - inspirograph-network
        restart: always
    roggle-server:
        image: roggle-server-image
        container_name: roggle-server-container
        build:
            context: .
            dockerfile: ./roggle-server/Dockerfile
        networks:
            - inspirograph-network
        restart: always

volumes:
    inspirograph-mysql-volume:
    nginx-certs-volume:
    nginx-flash-briefings-volume:

networks:
    inspirograph-network:
        driver: bridge