version: "2.4"

services:
  nginx:
    volumes:
      - ./nginx/deployed:/etc/nginx
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: always
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot:v1.7.0
    container_name: certbot
    volumes:
      - type: bind
        source: ./certbot/conf
        target: /etc/letsencrypt
      - type: bind
        source: ./certbot/www
        target: /var/www/certbot
    restart: always
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  php:
    restart: always

  mysql:
    restart: always

  roggle-server:
    restart: always

  nodechat-server:
    restart: always
