version: '3.7'

services:
    nginx:
        image: nginx:1.15.2-alpine
        container_name: nginx-container
        ports:
            - '80:80'
            - '443:443'
            - '18734:18734'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/certs:/etc/nginx/certs
            - ./nginx/logs:/etc/nginx/logs
            - ./node_modules/@nathanfriend/website-3.0:/etc/nginx/html
            - ./node_modules/@nathanfriend/inspirograph:/etc/nginx/html/inspirograph
            - ./node_modules/@nathanfriend/roggle:/etc/nginx/html/roggle
        networks:
            - inspirograph-network
        restart: always
    php:
        image: inspirograph-php-image
        container_name: inspirograph-php-container
        build: ./php
        volumes:
            - ./node_modules/@nathanfriend/inspirograph:/etc/nginx/html/inspirograph
        networks:
            - inspirograph-network
        restart: always
    mysql:
        image: inspirograph-mysql-image
        container_name: inspirograph-mysql-container
        build: ./mysql
        volumes:
            - ./mysql/conf:/etc/mysql/conf.d
            - inspirograph-mysql-volume:/var/lib/mysql
        networks:
            - inspirograph-network
        restart: always
    roggle-server:
        image: roggle-server-image
        container_name: roggle-server-container
        build:
            context: .
            dockerfile: ./roggle-server/Dockerfile
        networks:
            - inspirograph-network
        restart: always

volumes:
    inspirograph-mysql-volume:

networks:
    inspirograph-network:
        driver: bridge